feat: add previews for courses/instructors (WIP)
icssc/peterportal-api-next pull request #119
Opened 2023-12-28 09:26 UTC by ecxyzzy

TODO before merging: copy dev schema courses/instructors table to prod.

2023-12-30 12:45 UTC, ap0nia requested changes
Good stuff 💪 
I left mostly database design considerations lol. The code looks fine; once it's clear what how we'd like the database to be organized, I think it's good to merge.

2023-12-30 12:45 UTC, ap0nia commented on apps/api/src/lib/utils.ts
>      prerequisiteTree: course.prerequisiteTree as unknown as PrerequisiteTree,
It seems to work for me without the first assertion to unknown.

```suggestion
    instructors: course.instructors as InstructorPreview[],
    prerequisiteTree: course.prerequisiteTree as PrerequisiteTree,
```

2023-12-30 12:45 UTC, ap0nia commented on apps/api/src/lib/utils.ts
> +    dependencies: course.dependencies as unknown as CoursePreview[],
```suggestion
    prerequisites: course.prerequisites as CoursePreview[],
    dependencies: course.dependencies as CoursePreview[],
```

2023-12-30 12:45 UTC, ap0nia commented on apps/api/src/routes/v1/graphql/schema/instructors.graphql
> +  shortenedName: String!
Maybe "displayName" or "shortName"? A past participle seems a bit verbose to me.

2023-12-30 12:45 UTC, ap0nia commented on libs/db/prisma/schema.prisma
> +  instructorHistory String[]
What if there was a "History" table that joined "Course" and "Instructor"? It would have a primary key of (course ID, instructor ID, and term) or something.
Idk if it's worth the extra work, but it would enable the ability to query the history of an instructor, i.e. to see if they have a good track record.

2023-12-30 12:45 UTC, ap0nia commented on libs/db/prisma/schema.prisma
> +  geList            String[]
One cool idea I've seen before is having a table of constants or enum of some sort. Then represent the GE List as a binary number. So if there are 8 GEs, the binary `10110000` would indicate that GEs 1, 3, 4 are represented by this entry.

2023-12-30 12:45 UTC, ap0nia commented on libs/db/prisma/schema.prisma
> +  prerequisites     Json        @default("[]")
I feel like this could actually be derived from a table? For example, a "Prerequisites" table that mapped course ID (prerequisite) to course ID (prerequisite for), uniquely keyed on those two columns.

To find a course's prerequisites given its course ID, search by the "prerequisite for" column with the same ID.
To find the courses that a course satisfies prerequisites for, search by the "prerequisite" column with the same ID.

I do realize that this is scrapped data and representing it as JSON is pretty minimal overhead on the backend complexity. But since we're scrapping it anyways, maybe we could store it optimally?

2023-12-30 12:45 UTC, ap0nia commented on tools/registrar-scraper/src/instructor-scraper/index.ts
> +  [ucinetid: string]: Omit<Instructor, "courses">;
I prefer using records if there's no information to preserve.
```suggestion
  Record<string, Omit<Instructor, "courses">>
```
 The main reason I use the mapped is to preserve interface information.

```ts
type MyType = {
  /** JSDoc for property a */
  a: string,
  /** JSDoc for property b*/
  b: string,
}

type DerivedType = Record<keyof MyType, any>
// Lost all of the JSDoc info.
type DerivedTypeA = DerivedType["a"]

type BetterDerived = { [k in keyof MyType]: MyType[k]}
// The JSDoc is preserved.
type BetterDerivedA = BetterDerived["a"]

If the key itself is a string, then there isn't any JSDoc information to preserve anyways.
```

2023-12-30 12:45 UTC, ap0nia commented on tools/registrar-scraper/src/instructor-scraper/index.ts
> +  const instructorPromises: Promise<[string, Omit<Instructor, "courses">]>[] = [];
Could we extract the `Omit<Instructor, "courses">` type? Maybe like "ScrappedInstructor"?

2023-12-30 12:45 UTC, ap0nia commented on tools/registrar-scraper/src/index.ts
> +  }
Functional programming 😎 
```suggestion
  const newCourses = Object.values(courses).map(course => {
    return {
      ...course,
      prerequisiteTree: course.prerequisiteTree as object,
      instructors: course.instructorHistory
        .map((x) => instructors[x])
        .filter((x) => x)
        .map(({ ucinetid, name, shortenedName }) => ({ ucinetid, name, shortenedName })),
      prerequisites: course.prerequisiteList
        .map((x) => courses[x.replace(/ /g, "")])
        .filter((x) => x)
        .map(({ id, title, department, courseNumber }) => ({
          id,
          title,
          department,
          courseNumber,
        })),
      dependencies: course.prerequisiteFor
        .map((x) => courses[x.replace(/ /g, "")])
        .filter((x) => x)
        .map(({ id, title, department, courseNumber }) => ({
          id,
          title,
          department,
          courseNumber,
        })),
    }
  })
```

2023-12-30 12:45 UTC, ap0nia commented on tools/registrar-scraper/src/index.ts
> +  }
```suggestion
  const newInstructors = Object.values(instructors).map(instructor => {
    return {
      ...instructor,
      courseHistory: instructor.courseHistory as object,
      courses: Object.keys(instructor.courseHistory!)
        .map((x) => courses[x.replace(/ /g, "")])
        .filter((x) => x)
        .map(({ id, title, department, courseNumber }) => ({
          id,
          title,
          department,
          courseNumber,
        })),
    }
  })
```

2024-01-10 18:12 UTC, ecxyzzy reviewed
Thanks for the feedback, I've incorporated most of the suggestions.

For posterity, we discussed the schema issues in DMs. We may consider in the future to use actual SQL relations, but the current solution provides the best performance since joins result in additional overhead.

2024-01-10 18:12 UTC, ecxyzzy commented on libs/db/prisma/schema.prisma
> +  geList            String[]
Good idea, I think eventually we will want to migrate to this model.

2024-01-16 19:53 UTC, ap0nia approved these changes
🚀

2024-01-16 19:53 UTC, ap0nia commented on apps/api/src/lib/utils.ts
> +} from "@peterportal-api/types";
For clarity, I like to prefix any type-only imports with `type`. This is actually enforceable through tsconfig via the [importsNotUsedAsValues](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues) setting, so it's not too important to do right now. It would be better to turn on the setting and open a PR that fixes the errors.

2024-01-16 19:53 UTC, ap0nia commented on tools/registrar-scraper/src/index.ts
> +      .filter((x) => x)
Slightly more efficient because we don't have to allocate the filter function multiple times, and a bit more legible because it's clear we're filtering for non-falsy values.

```suggestion
      .filter(notNull)
```

2024-01-16 20:04 UTC, ecxyzzy commented on apps/api/src/lib/utils.ts
> +} from "@peterportal-api/types";
I like using `import type` as well but sometimes I miss it. Nice catch and thanks for letting me know that this exists; I'll make an issue for it.

2024-01-16 20:46 UTC, ap0nia commented on apps/api/src/lib/utils.ts
> +} from "@peterportal-api/types";
Oh, yeah I guess it's supposed to be [verbatimModuleSyntax](https://www.typescriptlang.org/tsconfig#verbatimModuleSyntax) now.

2024-01-17 07:29 UTC, merged