122 add filtering by restriction code to websoc endpoint
icssc/peterportal-api-next pull request #130
Opened 2024-02-10 00:49 UTC by andrew-wang0

# Summary

Added filtering by restriction code to websoc REST & GraphQL endpoints using the ```excludeRestrictionCodes``` parameter.
* Included restrictionCodes in db schema & scraper
* Added excludeRestrictionCodes to query parameters for REST & GraphQL
 
---
Example queries:

To exclude sections that include restriction code 'A'
```http
GET http://localhost:8080/v1/rest/websoc?year=2024&quarter=Winter&ge=GE-4&excludeRestrictionCodes=A
```
To exclude sections that include restriction code 'X' or 'L' (or both)
```http
GET http://localhost:8080/v1/rest/websoc?year=2024&quarter=Winter&ge=GE-4&excludeRestrictionCodes=X,L
```

# Issues

Closes #122

2024-02-10 00:52 UTC, KevinWu098 commented
🤤

2024-02-10 02:17 UTC, KevinWu098 commented
Will start writing the feature with this staging instance 🫡, hopefully sus out some bugs while I'm at it

2024-02-13 19:25 UTC, ecxyzzy requested changes
Looks good enough for initial testing. However, this only filters out requests that go through the cache; requests that result in invoking the WebSoc proxy aren't filtered out properly.

cc: @KevinWu098 (stakeholder)

2024-03-13 20:21 UTC, andrew-wang0 commented
> Looks good enough for initial testing. However, this only filters out requests that go through the cache; requests that result in invoking the WebSoc proxy aren't filtered out properly.

I believe filtering should work for the WebSoc proxy now!

@ecxyzzy 
@KevinWu098

2024-04-24 23:06 UTC, ap0nia requested changes
It looks pretty good at a cursory glance! 🚀

2024-04-24 23:06 UTC, ap0nia commented on apps/api/src/routes/v1/rest/websoc/+endpoint.ts
> +            return { ...department, courses: department.courses };
How come it says `department.courses = ...` and then `return { ...department, courses: department.courses }`. It looks like `department.courses` should be updated properly, so there's no need to shallow copy anything?

i.e. I imagine it would look like this.

```ts
department.courses = department.courses.map(...).filter(...)
return department
```

2024-04-24 23:56 UTC, andrew-wang0 commented on apps/api/src/routes/v1/rest/websoc/+endpoint.ts
> +            return { ...department, courses: department.courses };
Oops. good catch! fixed in following commit.

2024-05-15 15:29 UTC, ecxyzzy approved these changes
LGTM! :rocket:

2024-05-15 15:29 UTC, merged