feat: implement WebSoc scraping and RDS-backed endpoint (WIP)
icssc/peterportal-api-next pull request #21
Opened 2023-03-10 06:50 UTC by ecxyzzy

Closes #11.

2023-03-10 09:18 UTC, bevm0 commented on tools/websoc-api-next/index.ts
>  /* region Constants */
```suggestion
//-----------------------------------------------------------------------------------
// START Constants
//-----------------------------------------------------------------------------------
```
My engineering verilog classes had lots of comments like this and they've kinda grown on me lol

2023-03-10 14:41 UTC, MinhxNguyen7 commented
How much faster is that?

2023-03-10 14:41 UTC, MinhxNguyen7 commented
How much faster is that?

2023-03-16 01:57 UTC, bevm0 commented on api/routes/websoc/build.mjs
>              await Promise.all(
Can this array be stored as a variable at the top of the file with a descriptive comment?

2023-03-16 02:03 UTC, bevm0 commented on api/routes/websoc/build.mjs
> +                "../../../node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node"
If possible, I'd like to look into somehow using node resolution to resolve these paths, i.e. the same resolution that `yarn` uses to somehow find the prisma schema.

For now, a compromise might be to store these strings as descriptive constants, e.g.
```ts
/**
 * Output of `prisma generate`
 */
const generatedPrisma = '../../node_modules/.prisma/client`
```

2023-03-16 02:11 UTC, bevm0 commented on api/routes/websoc/build.mjs
I'm not a big fan of the "immediately invoked lambda function" pattern because there are too many parentheses lol. I think it's lot simpler to immediately parse and understand if it's a vanilla function declaration + invocation. e.g.
```ts
async function buildApp() {
  // esbuild this app
}

// just call the function when the script runs
buildApp()
```

2023-03-16 02:14 UTC, bevm0 commented on api/routes/websoc/build.mjs
>          name: "copy",
It's up to preference, but could we have separate plugins for dealing with prisma vs. dealing with external dependencies?
We might be able to extract the prisma plugin altogether into its own monorepo package.

2023-03-16 02:22 UTC, bevm0 commented on api/routes/websoc/schema.ts
> +      .optional(),
I'm not sure if we'd like to continue discussing this, but this doesn't feel like idiomatic schema usage.

The reason the `optional` is appended onto the end is to force the output type to be possibly undefined; this is fundamentally incorrect because this type should be entirely dependent on the return type of `normalizeValue`. 

I imagine the scenario is something like this: `courseNumber` can be a string, string array, or undefined. After we normalize it, it'll be a sorted array or undefined still. In that case, `normalizeValue` should have a return type that's union-ed with undefined. `optional` is generally meant to parse the input **before** the transformation step. 

TLDR: Chaining a final `optional` incorrectly type-asserts the return type of `normalizeValue`, and we should adjust `normalizeValue` to return `T | undefined`, and then drop all trailing `optional` calls after a `transform`.

2023-03-16 03:49 UTC, bevm0 requested changes
Overall, I think everything looks pretty solid. 👍 

I just wanted to discuss some of the comments I brought up before merging everything in.

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/index.ts
>          for (;;) {
```suggestion
        while (queries.length && retries < 3) {
```
Can we extract the "failed to respond error" outside? e.g.
```ts
while (queries.length && retries < 3) {
  // try fetching queries
}

// now that we're done with all the attempts, check if an error condition has occurred
if (queries.length && retries >= 3) {
  createErrorResult(...)
}
```
This simplifies the logic in the loop body.

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/index.ts
> +
```suggestion
let failed: WebsocAPIOptions[] = [];
```
We can move the failed array outside as well.

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/index.ts
Overall, this file looks much cleaner than the very first implementation. Good work! :rocket: :sunglasses: :fire:

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +const SLEEP_DURATION = 5 * 60 * 1000; // 5 minutes
```suggestion
/**
 * The duration to sleep between scraping runs, or to wait before querying the
 * database for terms to scrape on demand if there were none in the last query.
 * default: 5 minutes
 */
const SLEEP_DURATION = 5 * 60 * 1000;
```

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/lib.ts
> +const lexOrd = (a: string, b: string): number => (a === b ? 0 : a > b ? 1 : -1);
This would be significantly better to me as `lexOrder`, but I'm fully aware that prettier will force this into 2 lines with those extra characters lol :sob:

I don't really like the 80 default default print width for prettier, I think 90-100 characters is perfectly fine and much more standard.

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/lib.ts
> +export const notNull = <T>(x: T): x is NonNullable<T> => x != null;
This honestly might be worth extracting into a completely miscellaneous package of utils, e.g.
```ts
// packages/utils/src/index.ts

/**
 * type guard that asserts input is defined
 */
export const notNull = <T>(x: T): x is NonNullable<T> => x != null;


// api/routes/websoc/lib.ts
import { notNull } from '@packages/utils'
```
Same for the sleep function.

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/lib.ts
> +      break;
```suggestion
    case undefined:
       AND.push({ cancelled: false });
      break;
    case "Exclude":
      AND.push({ cancelled: false });
      break;
```
I get what it's supposed to do, but I think it's nice to have defined behavior for each case, even if they're duplicated.

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/lib.ts
> +              lte: parseInt(code.split("-")[1]),
```suggestion
              gte: parseInt(code.split("-")[0], 10),
              lte: parseInt(code.split("-")[1]), 10,
```

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/lib.ts
> +            .join(","),
```suggestion
          sectionCodes: query.sectionCodes?
            .slice(k * 5, (k + 1) * 5)
            .join(",") || [],
```
I generally don't like doing an early `or` because I could negate short circuiting. e.g. If `query.SectionCodes` is undefined, then it can immediately short circuit to `[]`, whereas creating the array early will result in it being sliced and joined.

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/lib.ts
> +          parseInt(b.courseNumber.replace(/\D/g, ""));
```suggestion
          parseInt(a.courseNumber.replace(/\D/g, ""), 10) -
          parseInt(b.courseNumber.replace(/\D/g, ""), 10);
```

2023-03-16 03:49 UTC, bevm0 commented on api/routes/websoc/lib.ts
> +          (a, b) => parseInt(a.sectionCode) - parseInt(b.sectionCode)
```suggestion
          (a, b) => parseInt(a.sectionCode, 10) - parseInt(b.sectionCode, 10)
```

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +  );
```suggestion
  const termDateData = await Promise.all(
    [
      ...(Array(3).keys()).map((x) =>
        getTermDateData((x + date.getFullYear() - 1).toString()
      )
    ])
  const quarterDates = {...termDateData}
```
I'm not sure of the reasoning behind the original code, but I was wondering if it could be simplified to something like this?

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +  );
```suggestion
  type TermEntry = [string, Term]

  const terms = await getTerms()
  const termEntries = terms
    .map((term) => term.shortName)
    .filter((term) => Object.keys(quarterDates).includes(term))
    .filter((term) => date <= quarterDates[term].finalsStart)
    .map((term) => {
      const termEntry: TermEntry = [term, { year: term.split(" ")[0], quarter: term.split(" ")[1] }]
      return termEntry
    })
  return Object.fromEntries(termEntries);
```
This sequence is more verbose and uses additional variables, but I think it really aids with logical clarity. It's also easier to view type definitions of each step to see how data is transformed to produce the output.

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +  const deptCodes = (await getDepts())
```suggestion
 const depts = await getDepts();
 
  // All departments to scrape.
  const deptCodes = depts
```

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +  }
Can you employ a similar strategy to the `api/routes/websoc/index.ts` file with the `failed` array, using a `while` loop instead of a `for` loop + `break`?

I like the `while` loop in these scenarios because it's immediately clear what the break condition is.

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +              const sectionCode = parseInt(section.sectionCode);
```suggestion
              const sectionCode = parseInt(section.sectionCode, 10);
```

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +                    ),
Extract the days array somewhere outside

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +                    })(),
Extract this into a defined function; and make sure `parseInt` is always using base 10

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +                  })(),
Extract this into a named function, or just inline the logic

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +            for (const section of course.sections) {
Prefer `forEach` when iterating over arrays. I *feel* like this could be expressed more succinctly as an accumulator + map function. Idk for sure tho, and I might just take a look at it myself later.

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +        }
Yeah same thing here, prefer `forEach` when iterating over arrays.

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +(async function main() {
Could we invoke this function normally at the end of the file?

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +      await scrape(name, term);
```suggestion
    Promise.all([
      Object.entries(termsInScope).map(([name, term]) => scrape(name, term);
    ])
```
Faster in parallel.

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +          await scrape(name, term);
Same `Promise.all` strat I mentioned above.

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +      );
```suggestion
      const websocTerms =  await prisma.websocTerm.findMany({
          where: { timestamp: { gte: now } },
          select: { year: true, quarter: true },
        })
      const termsOnDemandEntries = websocTerms.map((x) => [`${x.year} ${x.quarter}`, x]);      
      const termsOnDemand = Object.fromEntries(termsOnDemandEntries);
```
Process is clearer.

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +      }
`Promise.all`

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +    for (;;) {
```suggestion
    while (true) {
```
Idk, I just don't like `for (;;)` lol.

I think it could be worth looking into using pm2's auto-restart with delay as opposed to an infinite loop. We'd be able to manage the instance and adjust the delay, restart conditions, etc. more easily. Encapsulating the entire program as an infinite loop just doesn't feel like the best long-term solution.

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +                    parseInt(section.maxCapacity),
```suggestion
                    parseInt(section.numCurrentlyEnrolled.totalEnrolled, 10) >
                    parseInt(section.maxCapacity, 10),
```

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +                  maxCapacity: parseInt(section.maxCapacity),
```suggestion
                  maxCapacity: parseInt(section.maxCapacity, 10),
```

2023-03-16 03:49 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +                  sectionCode: parseInt(section.sectionCode),
```suggestion
                  sectionCode: parseInt(section.sectionCode, 10),
```

2023-03-16 05:36 UTC, MinhxNguyen7 reviewed
I don't have much to say other than style because I'm not that familiar with all this. Consider it an outsider's/newbie's perspective on your code. I only looked closely at the scraping code, and @bevm0 got most of what I was thinking. Otherwise, LGTM.

2023-03-16 05:36 UTC, MinhxNguyen7 commented on api/routes/websoc/build.mjs
Yeah, I'd go as far as to argue that it's bad style because the syntax is not immediately clear.

2023-03-16 05:36 UTC, MinhxNguyen7 commented on tools/websoc-scraper-v2/index.ts
> +    for (;;) {
for(;;) is cursed

2023-03-16 05:36 UTC, MinhxNguyen7 commented on tools/websoc-scraper-v2/index.ts
> +      await scrape(name, term);
We might get rate-limited if we do that. This ensures that we finish our request for a department before we ask for another one. Speed is not our friend when scraping WebSOC.

2023-03-16 05:36 UTC, MinhxNguyen7 commented on tools/websoc-scraper-v2/index.ts
> +        }
I would have an `else` here and output a logger warning. I know that it _shouldn't_ be possible to have an input that has neither department nor ge, and that this would skip it, so it doesn't really matter, but WebdocAPIOptions does technically allow for it if there's an instructor search. I prefer to be explicit, but it's up to you.

2023-03-16 20:25 UTC, ecxyzzy reviewed
I appreciate the feedback, especially the outsider perspective. One of the goals of Projects is to make the entry barrier for outside contributors as low as possible, and reviews in that view definitely help to work towards that goal.

2023-03-16 20:25 UTC, ecxyzzy commented on tsconfig.json
> +    "resolveJsonModule": true,
I believe I may have added this while testing the scraper with JSON output. Is it bad practice to include this in a production-environment tsconfig?

2023-03-16 20:25 UTC, ecxyzzy commented on tools/websoc-scraper-v2/index.ts
> +      await scrape(name, term);
Minh is correct—we _don't_ want all scraping tasks to run in parallel because that will almost certainly get us ratelimited. Writing it this way ensures that each scraping task finishes its 5-minute wait before we start the next one.

2023-03-16 20:25 UTC, ecxyzzy commented on api/routes/websoc/schema.ts
> +const days = ["Su", "M", "Tu", "W", "Th", "F", "Sa"];
That's fine in a vacuum but WebSoc only recognizes these specific identifiers (among others that we don't intend to support) for the days of the week, so I think it's fine to hardcode them here.

2023-03-16 20:25 UTC, ecxyzzy commented on api/routes/websoc/schema.ts
> +    department: z.string().optional(),
That would require us to cache the list of available departments somewhere, or query WebSoc every time we got a request. I don't think it's necessary, since invalid department codes will just result in the `websoc-api-next` module returning `{ schools: [] }`.

2023-03-16 20:25 UTC, ecxyzzy commented on db/prisma/schema.prisma
> +  days        Json
MySQL/MariaDB does not support native scalar arrays. IMO it's unnecessary to build another many-to-many relation just for storing what day(s) a section meets on, since Prisma supports filtering on an array value for `Json` fields.

2023-03-16 20:25 UTC, ecxyzzy commented on db/prisma/schema.prisma
> +  timestamp DateTime
I believe the `timestamp` field is relatively standard to denote when the row was last updated. However, I can see how its meaning could be ambiguous here. Do you think `lastUpdated` would make more sense for this and `WebsocSection`?

2023-03-16 20:57 UTC, bevm0 commented on api/routes/websoc/schema.ts
> +const days = ["Su", "M", "Tu", "W", "Th", "F", "Sa"];
Oh ok, I thought these were just arbitrary. Sounds good!

2023-03-16 20:58 UTC, bevm0 commented on tsconfig.json
> +    "resolveJsonModule": true,
No it's perfectly fine. I just like having a minimal tsconfig; I do that as a mini-game to learn more about what each option does and when I need it lol

2023-03-16 21:05 UTC, ecxyzzy reviewed
Thanks GitHub for not auto-displaying large diffs and making me think that the files didn't have comments. Real helpful of you.

Everyone's comments should now be addressed.

2023-03-16 21:05 UTC, ecxyzzy commented on tools/websoc-scraper-v2/index.ts
> +    for (;;) {
ESLint doesn't like constants in while loop conditions. That alone is probably a sign to refactor this into a script that runs only once and have pm2 manage the restart conditions.

2023-03-16 22:34 UTC, bevm0 commented on api/routes/websoc/build.mjs
It *is* a documented pattern https://developer.mozilla.org/en-US/docs/Glossary/IIFE.
So it's mostly up to preference/scenario dictating its use case.

2023-03-17 20:09 UTC, MinhxNguyen7 commented on db/prisma/schema.prisma
> +  timestamp DateTime
`lastUpdated` would make sense. Since `timestamp` is standard, I think it's fine to leave it like that well. It's up to you.

2023-03-19 02:12 UTC, MinhxNguyen7 commented on api/routes/websoc/build.mjs
Right, but none of the use cases (compared to definition + invocation) apply here. I suppose since it's documented, it's not "bad syntax" _per se_

2023-03-20 02:15 UTC, bevm0 requested changes
Ok, this is a lot of content, but I left comments regarding code cleanup and project considerations. I'm not too aware of the actual state of the project at this point, so let me know if I can help out in testing or something. :rocket:

2023-03-20 02:15 UTC, bevm0 commented on api/routes/websoc/schema.ts
> +      .optional(),
```suggestion
      .transform(flattenStringsAndSplit),
```
`flattenStringsAndSplit` says it can return undefined, so I think this is redundant. Same for any other `optional` that are chained after `transform`.

2023-03-20 02:15 UTC, bevm0 commented on api/routes/websoc/index.ts
> +    case "HEAD":
Oh I didn't know that lol, ok sounds good

2023-03-20 02:15 UTC, bevm0 commented on api/routes/websoc/index.ts
> +          await sleep(1000 * 2 ** retries++);
I'm confident the `createErrorResult` can be moved outside of the loop body, since the loop won't exceed that many retries before terminating. The `if (!queries.length) break` bothers me because it seems like we're defining a stop condition for the for loop that will never become true. A compromise might be to apply a condition to the sleep, e.g.
```ts
if (queries.length) await sleep(1000 * 2 ** retries++)
```

Now we have a for loop that has two valid conditions that can definitely be triggered (also this supports the reasoning that we want to move the error result outside), and we handle any other cases appropriately.

2023-03-20 02:15 UTC, bevm0 commented on api/routes/websoc/lib.ts
> +export const notNull = <T>(x: T): x is NonNullable<T> => x != null;
My bad, I forgot to respond to this. Resolved on Discord...

We can move internal packages to a root level `libs` directory, e.g. database, ddb, utils, etc.
Public packages can stay in the `packages` directory, e.g. peterportal-types

And if desired, we can configure scoping on internal packages to make them easier to find.
This entails:
1. Assigning their name in the package.json, e.g. `"name": "@libs/db"`
2. Configuring their path alias in the project root's tsconfig, e.g. compilerOptions -> paths.
3. Configuring other related settings in package.jsons? Idk how it works because I usually just define the path aliases manually for any build tools I use, instead of letting the monorepo handle it https://turbo.build/repo/docs/handbook/sharing-code/internal-packages#4-fix-main-and-types

2023-03-21 00:42 UTC, bevm0 approved these changes
Ok I think it's good

2023-03-21 00:42 UTC, bevm0 commented on api/routes/websoc/index.ts
> +        if (parsedQuery.cache && termExists) {
I changed this to "if cache enabled and term exists, find it in the database". I think that's the original intent?

2023-03-21 00:42 UTC, bevm0 commented on api/routes/websoc/index.ts
> +          if (queries.length) await sleep(1000 * 2 ** retries++);
Now it *will* go back to the top after every loop, and hit the defined stop conditions. But a specific behavior per loop is to sleep if there are more upcoming queries, so I handled that accordingly.

2023-03-21 00:42 UTC, bevm0 commented on api/routes/websoc/schema.ts
> +type TransformOutput = string[] | undefined;
So I can squeeze the function defs on one line

2023-03-21 00:42 UTC, bevm0 commented on api/routes/websoc/schema.ts
> +  return [...unique];
We don't actually need to sort the days, it's kind of a meme to do that; just turn it into an array

2023-03-21 00:42 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +                  ),
uci moment

2023-03-21 00:47 UTC, merged