feat: dockerize scraper (WIP)
icssc/peterportal-api-next pull request #26
Opened 2023-03-17 00:52 UTC by ecxyzzy

TODO:

- [ ] Investigate whether it is possible to SSH into the EC2 instance managed by ECS

2023-03-17 22:21 UTC, ecxyzzy commented
For the record, it is not possible without significant manual screwing-around (outside of CDK). Since the point of using CDK is to ensure that our infrastructure is replicable, there's not really much point in doing so.

We can however get the container to output logs to CloudWatch, so that's a win in my books.

2023-03-17 23:33 UTC, bevm0 commented on tools/cdk/app.ts
> +import { type StackProps, App } from "aws-cdk-lib";
```suggestion
import { App } from "aws-cdk-lib";
import type { StackProps } from "aws-cdk-lib";
```
Two reasons that I prefer this (that are mostly trivial)
1. Vim doesn't syntax highlight the mixed line properly for me lol
2. There's actually a prescribed import order by ESLint, and it's easier for me to fulfill them when I just split them up. https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md

2023-03-17 23:55 UTC, ecxyzzy commented
Scraper seems to not be reading the previous exit time properly, since it's scraping every term on start. Will do some more testing.

2023-03-18 00:19 UTC, bevm0 requested changes
I think this code is functional; it just needs finetuning to make sure everything is ready for production. Good work! 👍 🔥

2023-03-18 00:19 UTC, bevm0 commented on turbo.json
Is there a reason we don't have turborepo depend on all environment variables, and only specific ones?

2023-03-18 00:19 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +        ? parseInt(readFileSync("/tmp/websoc_scraper_v2").toString())
```suggestion
        ? parseInt(readFileSync("/tmp/websoc_scraper_v2").toString(), 10)
```
lol.

An alternative that has some overhead, but might bit marginally nicer is `z.coerce.number().parse(...)`, which can parse numeric strings into numbers.

2023-03-18 00:19 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +    if (curr.getDate() !== prev.getDate()) {
```suggestion
    if (curr.getDate() > prev.getDate()) {
```

2023-03-18 00:19 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
> +    );
```suggestion
    const termsOnDemandEntries: TermEntry[] = websocTerms
      .map((x) => [`${x.year} ${x.quarter}`, x])
      .filter(([name]) => {
        if (!(name in termsInScope)) {
          logger.info(`Term ${name} requested but not in scope, skipping`);
          return false;
        }
        return true;
    })
```
I think you could actually define the type upfront and then the returned arrays are forced to comply. Also, I think you can remove the `continue` block in the code below just by filtering out the invalid terms early.

2023-03-18 00:19 UTC, bevm0 commented on tools/websoc-scraper-v2/index.ts
>        }
```suggestion
```
What if we just filter out these cases early?

2023-03-18 00:35 UTC, ecxyzzy commented on tools/websoc-scraper-v2/Dockerfile
> +FROM node:16-bullseye-slim
I tried using the Alpine image at first, but it didn't play nice with my laptop's DNS settings (probably due to a quirk in musl libc which it uses). A glibc distro-based container Just Works, and is not that much larger than an Alpine image.

2023-03-18 00:35 UTC, ecxyzzy commented on tools/websoc-scraper-v2/build.mjs
> +    TZ="America/Los_Angeles"`
If I understand the documentation correctly, Docker recommends against injecting secrets in the `Dockerfile`. And in any case the script already `import`s `dotenv`, so there's not much of a difference IMO.

2023-03-18 00:36 UTC, bevm0 commented on tools/websoc-scraper-v2/Dockerfile
> +FROM node:16-bullseye-slim
Cool! Maybe I'll try using it instead of the vanilla Node image :skull:

2023-03-18 00:42 UTC, bevm0 commented on turbo.json
Oh I see, these env variables don't come from a `.env` file. Ok sure, this sounds good then!

2023-03-18 01:12 UTC, bevm0 commented on tools/websoc-scraper-v2/build.mjs
> +    TZ="America/Los_Angeles"`
Resolved by setting the container's runtime environment variables in the cdk app.

2023-03-18 01:14 UTC, bevm0 approved these changes
The implementation looks solid!

2023-03-18 01:21 UTC, ecxyzzy commented
Will hold off on merging this until we have a successful deploy, because the scraper's CloudFormation stack is currently stuck in limbo.

2023-03-19 23:38 UTC, bevm0 approved these changes
I think everything looks fine, great work!👍 

I just left some questions up for discussion.

2023-03-19 23:38 UTC, bevm0 commented on tools/cdk/websocScraperV2Stack.ts
> +    );
I think this is perfectly fine. These exact same commands are being run in the same place where the rest of the container is getting set up.

The issue I had with the shell script was that it seemed out of place in our Node + Docker setup. I felt that those commands should've been encapsulated by either the CDK setup or the Dockerfile

2023-03-19 23:38 UTC, bevm0 commented on tools/cdk/websocScraperV2Stack.ts
> +    // https://github.com/aws/aws-cdk/issues/18179#issuecomment-1150981559
```suggestion
  /** @see {@link https://github.com/aws/aws-cdk/issues/18179#issuecomment-1150981559} */
```
JSDoc is fun

2023-03-19 23:38 UTC, bevm0 commented on tools/cdk/websocScraperV2Stack.ts
> +      },
I noticed there was also an `environment_file` or some similar option. Is there a strict preference or requirement for either? It might be easier to just have the container share the same env file as the project, if that has the same effect.

2023-03-19 23:38 UTC, bevm0 commented on tools/websoc-scraper-v2/ecosystem.config.js
> +      script: "tsx --expose-gc index.ts",
I'm not sure if we went over this before, but is there a preference for tsx over ts-node? https://www.npmjs.com/package/ts-node

I usually just use tsx because it seems to work, but ts-node has those juicy npm stars...:eyes:

2023-03-19 23:38 UTC, bevm0 commented on tools/cdk/websocScraperV2Stack.ts
> +      throw new Error("Scraper database URL not provided. Stop.");
Is this a special requirement for this cdk script over others? 

While it's definitely good practice to watch out for these conditions, (for better or worse) I usually prefer to avoid adding pre-emptive error checking because it confuses me whether those errors have occurred or not and whether the checking was pre-emptive or reactive.

2023-03-20 00:20 UTC, ecxyzzy commented on tools/cdk/websocScraperV2Stack.ts
> +      },
When running in GitHub Actions we won't have an env file, unless we dump the environment into a file in the workflow itself (which feels redundant). In any case the scraper env needs to be distinct from the project env, since it has its own database username/password (for least privilege purposes) and V8 heap options.

2023-03-20 00:20 UTC, ecxyzzy commented on tools/websoc-scraper-v2/ecosystem.config.js
> +      script: "tsx --expose-gc index.ts",
`tsx` just works, especially since we use ES6 modules exclusively. As you know the corresponding `ts-node` invocation is very verbose.

2023-03-20 00:20 UTC, ecxyzzy commented on tools/cdk/websocScraperV2Stack.ts
> +      throw new Error("Scraper database URL not provided. Stop.");
In this case, deploying without the database URL specified will just burn our EC2 time since the deployed container will repeatedly try and fail to connect to the database. So I think it's necessary here IMO.

2023-03-20 00:20 UTC, merged

2023-03-20 01:21 UTC, bevm0 commented on tools/websoc-scraper-v2/ecosystem.config.js
> +      script: "tsx --expose-gc index.ts",
Oh right, I remember the first time you showed me and I was wondering why the CLI for tsx seemed so much nicer lol