pnpm
icssc/peterportal-api-next pull request #46
Opened 2023-05-30 23:52 UTC by ap0nia

Added pnpm and attempted to fix any TS and module resolution issues

2023-05-31 14:48 UTC, ap0nia commented on .eslintrc.cjs
> +/** @type {import('eslint').Linter.Config} */
Using JSDoc + JS config formats can actually give you type information for the ESLint and Prettier configurations, which is pretty neat. Otherwise, the settings should be the same.

2023-05-31 14:51 UTC, ap0nia commented on .prettierrc.cjs
> +
I left this note around when dealing with a full stack application w/TailwindCSS. It's up to your discretion whether it's worth leaving around.

2023-05-31 14:52 UTC, ap0nia commented on api/cdk/cdk.json
> +  "app": "npx tsx app.ts",
When invoking `cdk` from the terminal CLI directly, it doesn't have the context of node modules. Adding `npx` should allow the command to work when invoked from the terminal or with an npm command.

2023-06-06 05:25 UTC, ecxyzzy requested changes
See comments.

Also I probably won't re-review until after finals since the consequences of my actions caught up to me, so no need to rush on responding.

2023-06-06 05:25 UTC, ecxyzzy commented on api/cdk/cdk.json
> +  "app": "npx tsx app.ts",
Why not `pnpx` in this case? Genuine question, since I'm not as familiar as I'd like with the `pnpm` ecosystem.

2023-06-06 05:25 UTC, ecxyzzy commented on package.json
> +    "format": "prettier --write ."
Was there a reason for eliminating the global test/dev scripts? I know we don't have many tests at the moment but that is something I would like to change in the future, and also being able to run `npm run dev` from the root is great for testing e.g. the GraphQL endpoint using Apollo Sandbox, which is on the docs site.

2023-06-06 09:21 UTC, ap0nia commented on package.json
> +    "format": "prettier --write ."
Oh oops, I thought each sub-project had its own dev script; that's how I setup the routes with the custom framework.

I just removed test since I didn't see anything there, but I guess I'll just add it back :^)

2023-06-06 09:27 UTC, ap0nia commented on api/cdk/cdk.json
> +  "app": "npx tsx app.ts",
The main reason I've pondered over is that you're guaranteed to have npx because that's built in, but not always pnpx. But you should have pnpx if you're working on the project :shrug: 

I guess there's also the case that using npx everywhere is more consistent; the CLIs of the package managers can behave slightly differently for some reason, so maybe using a well-established one might be more predictable

2023-06-15 06:41 UTC, ecxyzzy commented
tfw you finally fix the build system and the message doesn't even render properly :upside_down_face:

2023-06-17 17:42 UTC, ecxyzzy approved these changes
LGTM now, excellent job and thanks for working with me on this!

2023-06-17 17:43 UTC, merged