Ant stack/dev
icssc/peterportal-api-next pull request #49
Opened 2023-06-17 20:43 UTC by ap0nia

TODO:
- [ ] Every single endpoint is a subproject that should be individually built by ESBuild to a `dist/index.js`
- [ ] Keep track of all of these projects in an `Object` or `Map`
- [ ] For each `dist/index.js`, create a new middleware router just for that route to enable hot-swapping per endpoint
- [ ] Chokidar needs to watch all of the discovered sub-project files
- [ ] Whenever a file changes, figure out which sub-project (i.e. endpoint) it belongs to, and recompile + re-assign the middleware router for that endpoint

2023-06-17 22:06 UTC, ap0nia commented
Oh oops, I have some of the old code from your create branch. How do I update it?

2023-06-17 22:09 UTC, ecxyzzy commented
You wanna have #48 merged into this branch and then merge the whole thing into `main`?

2023-06-17 22:11 UTC, ap0nia commented
Ok sure!

2023-06-17 23:36 UTC, ecxyzzy requested changes
Looks good. One minor issue, aside from logging consistency suggestions:

`findAllProjects` seems to double count the `/v1/rest/klein` endpoint and only that endpoint; not sure why. Can you recreate this, and if so is the solution literally just tossing it into a `Set` to dedupe?

2023-06-17 23:36 UTC, ecxyzzy commented on packages/ant-stack/src/cli/commands/dev.ts
> +    consola.log(`🚀 Express server listening at http://localhost:${config.port}`);
```suggestion
    consola.info(`🚀 Express server listening at http://localhost:${config.port}`);
```

2023-06-17 23:36 UTC, ecxyzzy commented on packages/ant-stack/src/cli/commands/dev.ts
> +    console.log("setting up router for ", endpoint);
```suggestion
    consola.info(`🚀 Setting up router for ${endpoint}`);
```

2023-06-17 23:38 UTC, ap0nia commented
Oh, yeah I was wondering why it would load some endpoint twice lol. Yeah let me use a set

2023-06-18 00:04 UTC, ecxyzzy approved these changes
LGTM now, awesome job!!

2023-06-18 00:04 UTC, merged