feat: fourmilier devops
icssc/peterportal-api-next pull request #96
Opened 2023-09-07 05:15 UTC by ap0nia

# Summary
Devops solved

# Next Steps
No more ~~cooking~~ devops please :pray:

2023-09-07 22:41 UTC, ecxyzzy commented on apps/api-fourmilier/bronya.config.ts
> +dotenv.config({ path: "../../.env" });
Should probably just use `dotenv/config` here since GitHub Actions just puts all the secrets in the runner environment.

2023-09-07 22:42 UTC, ecxyzzy commented on apps/api-fourmilier/bronya.config.ts
> +        SHADOW_DATABASE_URL: process.env["SHADOW_DATABASE_URL"] ?? "",
The shadow database URL isn't actually necessary.

2023-09-07 22:46 UTC, ecxyzzy commented on apps/api-fourmilier/package.json
> +  "funding": "https://github.com/icssc/peterportal-api-next",
```suggestion
```

2023-09-07 22:47 UTC, ecxyzzy commented on apps/api-fourmilier/package.json
> +  }
Dependencies and engines should all be pinned.

2023-09-07 22:51 UTC, ecxyzzy commented on apps/api-fourmilier/src/v1/rest/websoc/APILambdaClient.ts
> +  }
Is there actually any reason to keep this if the constructor is public and we have the `$connect` method? Or is the constructor being public not actually intentional?

2023-09-07 22:51 UTC, ecxyzzy commented on apps/api/package.json
> +    "@types/aws-lambda": "^8.10.119"
Pin pls

2023-09-07 22:51 UTC, ecxyzzy commented on libs/lambda/package.json
> +    "@types/aws-lambda": "^8.10.119"
Also pin pls

2023-09-07 22:54 UTC, ap0nia commented on apps/api/package.json
> +    "@types/aws-lambda": "^8.10.119"
Would you want me to just go through and pin everything real quick?

What if we just force ran renovate on the monorepo again :^)

2023-09-07 22:56 UTC, ap0nia commented on apps/api-fourmilier/src/v1/rest/websoc/APILambdaClient.ts
> +  }
Oh, I temporarily used `moduleResolution: "bundler"` in the tsconfig because the exports from my package weren't being resolved with `moduleResolution: "Node"`. This setting didn't allow top-level async, so I wrote a `$connect` method to initialize it in the async handler. I figured out what was wrong, and now we're using `moduleResolution: "Node"` again, which does allow me to just do `await APILambdaClient.new()`

I could remove this if we want to continue initializing with top-level await.

2023-09-07 22:58 UTC, ecxyzzy commented on libs/lambda/src/compress.ts
> +  }
I guess I should have documented it, but per the [relevant section](https://www.rfc-editor.org/rfc/rfc9110#section-12.5.3-10.1) in the HTTP Semantics RFC, if `Accept-Encoding` is not provided, then any encoding should be acceptable. So we should use gzip if it's greater than the compression threshold. We should only return the payload in plaintext if it's below the compression threshold, or if `Accept-Encoding` is the empty string.

2023-09-07 22:58 UTC, ecxyzzy commented on libs/lambda/src/compress.ts
> +  }
Logic error here maybe? Isn't this less than the minimum compression size?

2023-09-07 23:00 UTC, ap0nia commented on apps/api-fourmilier/bronya.config.ts
> +dotenv.config({ path: "../../.env" });
Oh, if this is intended to be run only during devops, then I can remove dotenv from the script altogether. I was deploying the canary version manually, so I needed to read from my local file system's env file.

2023-09-07 23:00 UTC, ap0nia commented on apps/api-fourmilier/bronya.config.ts
> +        SHADOW_DATABASE_URL: process.env["SHADOW_DATABASE_URL"] ?? "",
Should I completely remove it then?

2023-09-07 23:00 UTC, ap0nia commented on libs/lambda/src/compress.ts
> +  }
Oh, I copy/pasted the wrong line of code lol.

2023-09-07 23:02 UTC, ecxyzzy commented on package.json
> +    "dotenv": "^16.3.1",
Also also pin pls

2023-09-07 23:02 UTC, ecxyzzy commented on packages/types/package.json
> +  "funding": "https://github.com/icssc/peterportal-api-next",
```suggestion
```

2023-09-07 23:02 UTC, ecxyzzy commented on packages/websoc-fuzzy-search/package.json
> +    "peterportal-api-next-types": "workspace:1.0.0-rc.3"
Wait why does fuzzy search depend on types lol

2023-09-07 23:05 UTC, ap0nia commented on packages/websoc-fuzzy-search/package.json
> +    "peterportal-api-next-types": "workspace:1.0.0-rc.3"
This file apparently uses it https://github.com/icssc/peterportal-api-next/blob/fourmilier/packages/websoc-fuzzy-search/setup.ts

2023-09-07 23:06 UTC, ecxyzzy commented on tsconfig.json
> +    "module": "ESNext",
I was actually thinking of using [@tsconfig/node18](https://www.npmjs.com/package/@tsconfig/node18) and keeping `"module": "es2022"` and `"moduleResolution": "node"`. Thoughts?

2023-09-07 23:06 UTC, ecxyzzy commented on tsconfig.json
> -    },
Why did this get killed?

2023-09-07 23:09 UTC, ap0nia commented on tsconfig.json
> -    },
Because if TypeScript is setup and working properly, then this shouldn't be needed. The packages should be composed correctly (this entails properly detailing the "typesVersions" property in the package's package.json if it has exports from sub-directories)

"typesVersions" is read when using moduleResolution: Node; otherwise bundler, NodeNext, and Node16 will read the "exports" field.

2023-09-07 23:10 UTC, ap0nia commented on tsconfig.json
> +    "module": "ESNext",
I don't really care as long as top-level await is supported. Just having it available generally makes life easier :nerd_face:

2023-09-07 23:12 UTC, ecxyzzy commented on .npmrc
> -link-workspace-packages = true
Yeah this looks fine for all of the services; we were probably doing some off-label usage beforehand.

2023-09-07 23:13 UTC, ecxyzzy requested changes
Nice start, thank you so much for working on all of this. :pray: Some changes are still necessary though.

Also any reason you didn't just nuke the original API and add this as a drop-in? It should be fine as long as we don't merge before everything is complete.

2023-09-07 23:24 UTC, ap0nia commented
> Also any reason you didn't just nuke the original API and add this as a drop-in?
Not really, I was thinking of just keeping it around as a reference or something. I can remove it now if you'd like.

2023-09-07 23:26 UTC, ecxyzzy commented on apps/api-fourmilier/bronya.config.ts
> +dotenv.config({ path: "../../.env" });
I'm pretty sure the workspace root's `dev` script already injects development credentials. So yeah, I think this is unnecessary, as long as the API has a `dev` script.

2023-09-07 23:26 UTC, ecxyzzy commented on apps/api-fourmilier/bronya.config.ts
> +        SHADOW_DATABASE_URL: process.env["SHADOW_DATABASE_URL"] ?? "",
Yeah please do :pray:

2023-09-07 23:27 UTC, ecxyzzy commented on apps/api/package.json
> +    "@types/aws-lambda": "^8.10.119"
I think that's less hassle than rerunning renovate, so please do :pray:

2023-09-07 23:28 UTC, ecxyzzy commented on packages/websoc-fuzzy-search/package.json
> +    "peterportal-api-next-types": "workspace:1.0.0-rc.3"
That's a setup script and not actually included in the final bundle so it should probably go under devDeps.

2023-09-07 23:36 UTC, ecxyzzy commented
Yeah I think that would make sense, and then we could adapt the staging stuff accordingly as well.

2023-09-07 23:37 UTC, ecxyzzy commented on apps/api-fourmilier/src/v1/rest/websoc/APILambdaClient.ts
> +  }
Yeah I think the static async factory pattern makes the most sense since we have top-level await.

2023-09-07 23:37 UTC, ecxyzzy commented on tsconfig.json
> +    "module": "ESNext",
Will include it in my PR against this branch.

2023-09-08 16:49 UTC, ecxyzzy requested changes
Cooking :fire:

Some slight changes needed still; feel free to address them at your leisure. Will start on a PR for the graphql stuff soon™.

2023-09-08 16:49 UTC, ecxyzzy commented on apps/api/package.json
> +    "@uc-irvine/api": "workspace:^",
Already discussed privately but this should probably go under `@libs/ucirvine-api` or similar.

2023-09-08 16:49 UTC, ecxyzzy commented on apps/api/package.json
> +  "description": "core lambda api for peterportal api",
```suggestion
  "description": "The workspace for PeterPortal API",
```

2023-09-08 16:49 UTC, ecxyzzy commented on apps/docs/package.json
> -    "node": "18"
Is the engines field not that relevant for a workspace package.json?

2023-09-08 16:57 UTC, ap0nia commented on apps/docs/package.json
> -    "node": "18"
tbh, I have no idea lol. My impression is that it's only significant to the root workspace, since that's where installations originate (i.e. the root node_modules). 

Weighing the pros/cons of maintaining the "engines" field for all private projects: I think it isn't really worth it, especially since everything is pinned. i.e. If we ever change one engine, we should update everybody else's, despite them not actually doing anything. I guess this is only an issue if renovate doesn't take care of it automatically. I think I'm ok with maintaining fully fledged package.jsons for officially released packages, and then keeping them simpler for things that are internal.

2023-10-16 17:18 UTC, ecxyzzy approved these changes
Ship ittt!! :rocket: :rocket: :rocket: 

Once again thank you so much for working on this. DX is going to be fire going forward!

2023-10-16 17:18 UTC, merged